version: '3.9'

services:
  backend:
    build:
      context: ./python-backend
    ports:
      - "8765:8765"
    volumes:
      - ./python-backend:/app
    command: python main.py

  frontend:
    build:
      context: ./electron-frontend
    volumes:
      - ./electron-frontend:/app
      - /app/node_modules
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=${DISPLAY}
    depends_on:
      - backend
    command: yarn dev